from .CategorieSerializer import CategorieSerializer
from .EtudiantSerializer import EtudiantSerializer
from .FournisseurSerializer import FournisseurSerializer
from .GestionTicketSerializer import GestionTicketsSerializer
from .JourSerializer import JourSerializer
from .LoginSerializer import LoginSerializer
from .LotsTicketSerializer import LotsTicketSerializer
from .MouvementStockSerializer import MouvementStockSerializer
from .PeriodeSerializer import PeriodeSerializer
from .ProduitSerializer import ProduitSerializer
from .RapportSerializer import RapportSerializer
from .recuSerializer import RecuSerializer
from .ReservationSerializer import ReservationSerializer
from .StockSerializer import StockSerializer
from .TicketSerializer import TicketSerializer
from .TypeRapportSerializer import TypeRapportSerializer
from .UtilisateurSerializers import UtilisateurSerializer
from .VendeurSerializer import TicketVenduSerializer, LotSerializer, ArgentRemisSerializer
