# Generated by Django 5.1.5 on 2025-01-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idcategorie', models.IntegerField(db_column='idCategorie', primary_key=True, serialize=False)),
                ('nomcategorie', models.CharField(db_column='nomCategorie', max_length=25)),
            ],
            options={
                'db_table': 'categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idetudiant', models.IntegerField(db_column='idEtudiant', primary_key=True, serialize=False)),
                ('nometudiant', models.CharField(db_column='nomEtudiant', max_length=50)),
                ('prenometudiant', models.CharField(db_column='prenomEtudiant', max_length=45)),
            ],
            options={
                'db_table': 'etudiant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idfournisseur', models.CharField(db_column='idFournisseur', max_length=5, primary_key=True, serialize=False)),
                ('nomfournisseur', models.CharField(db_column='nomFournisseur', max_length=45)),
                ('contact', models.CharField(max_length=55)),
                ('dateajout', models.DateTimeField(blank=True, db_column='dateAjout', null=True)),
            ],
            options={
                'db_table': 'fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionTickets',
            fields=[
                ('idgestiontickets', models.BigAutoField(db_column='idGestionTickets', primary_key=True, serialize=False)),
                ('nbreticketvendu', models.IntegerField(db_column='nbreTicketVendu')),
                ('nbreticketrestant', models.IntegerField(db_column='nbreTicketRestant')),
                ('dategestionticket', models.DateField(db_column='dategestionTicket')),
                ('argentaremettre', models.FloatField(db_column='argentARemettre')),
                ('argentremis', models.FloatField(db_column='argentRemis')),
            ],
            options={
                'db_table': 'gestion_tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('idjour', models.IntegerField(db_column='idJour', primary_key=True, serialize=False)),
                ('nomjour', models.CharField(db_column='nomJour', max_length=10)),
            ],
            options={
                'db_table': 'jour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LotsTicket',
            fields=[
                ('idlots', models.BigAutoField(db_column='idLots', primary_key=True, serialize=False)),
                ('typelot', models.CharField(blank=True, db_column='typeLot', max_length=20, null=True)),
                ('nbretickets', models.IntegerField(db_column='nbreTickets')),
                ('prixlot', models.BigIntegerField(db_column='prixLot')),
                ('datecreation', models.DateTimeField(blank=True, db_column='dateCreation', null=True)),
            ],
            options={
                'db_table': 'lots_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('idmouvement', models.BigAutoField(db_column='idMouvement', primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datemouvement', models.DateTimeField()),
                ('estsortie', models.IntegerField()),
            ],
            options={
                'db_table': 'mouvement_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('idperiode', models.IntegerField(db_column='idPeriode', primary_key=True, serialize=False)),
                ('nomperiode', models.CharField(db_column='nomPeriode', max_length=10)),
            ],
            options={
                'db_table': 'periode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idproduit', models.CharField(db_column='idProduit', max_length=5, primary_key=True, serialize=False)),
                ('nomproduit', models.CharField(db_column='nomProduit', max_length=25)),
                ('quantitedisponible', models.DecimalField(db_column='quantiteDisponible', decimal_places=2, max_digits=10)),
                ('seuilcritique', models.DecimalField(db_column='seuilCritique', decimal_places=2, max_digits=10)),
                ('ration', models.FloatField(blank=True, null=True)),
                ('etat', models.CharField(max_length=10)),
                ('dateajout', models.DateTimeField(blank=True, db_column='dateAjout', null=True)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('idrapport', models.BigAutoField(db_column='idRapport', primary_key=True, serialize=False)),
                ('fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('daterapport', models.DateTimeField(db_column='dateRapport')),
            ],
            options={
                'db_table': 'rapport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('idrecu', models.BigAutoField(db_column='idRecu', primary_key=True, serialize=False)),
                ('daterecu', models.DateField(db_column='dateRecu')),
            ],
            options={
                'db_table': 'recu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idreservation', models.BigAutoField(db_column='idReservation', primary_key=True, serialize=False)),
                ('datereservation', models.DateField(db_column='dateReservation')),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idstock', models.IntegerField(db_column='idStock', primary_key=True, serialize=False)),
                ('datestock', models.DateField(db_column='dateStock')),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idticket', models.IntegerField(db_column='idTicket', primary_key=True, serialize=False)),
                ('prixticket', models.IntegerField(db_column='prixTicket')),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typerapport',
            fields=[
                ('idtyperapport', models.BigAutoField(db_column='idTypeRapport', primary_key=True, serialize=False)),
                ('nomtyperapport', models.CharField(db_column='nomTypeRapport', max_length=25)),
            ],
            options={
                'db_table': 'typerapport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idutilisateur', models.AutoField(db_column='idUtilisateur', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=20, null=True)),
                ('prenom', models.CharField(max_length=20)),
                ('motpasse', models.CharField(db_column='motPasse', max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone', models.CharField(max_length=25, unique=True)),
                ('role', models.CharField(max_length=19)),
                ('datecreation', models.DateTimeField(blank=True, db_column='dateCreation', null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
    ]
