# Generated by Django 5.1.5 on 2025-01-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typerapport',
            table='typeRapport',
        ),
    ]
