# Generated by Django 5.1.5 on 2025-02-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jour',
            options={},
        ),
    ]
