# Generated by Django 5.1.5 on 2025-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0002_alter_typerapport_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgentRemis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lot', models.CharField(choices=[('Petit-déjeuner', 'Petit-déjeuner'), ('Déjeuner', 'Déjeuner')], max_length=20)),
                ('nombre_lot', models.IntegerField()),
                ('montant', models.IntegerField(editable=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketVendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('Petit-déjeuner', 'Petit-déjeuner'), ('Déjeuner', 'Déjeuner')], max_length=20)),
                ('nombre_ticket', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
