# Generated by Django 5.1.5 on 2025-02-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0002_alter_jour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jour',
            options={'managed': False},
        ),
    ]
