# Generated by Django 5.1.5 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0003_argentremis_lot_ticketvendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='type_lot',
            field=models.CharField(choices=[('Déjeuner', 'Déjeuner'), ('Petit-déjeuner', 'Petit-déjeuner')], max_length=20),
        ),
    ]
